trigger:
  branches:
    include:
      - main

schedules:
  - cron: "0 6 * * 1"   # Runs every Monday at 6 AM UTC
    displayName: Weekly ETL Run
    branches:
      include:
        - main
    always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: |
    pip install -r requirements.txt
  displayName: 'Install Python packages'

- script: |
    python 5_Azure_DevOps_Automation/run_etl_and_alert.py
  displayName: 'Run ETL + Alert Script'
